### PR TITLE
Fixes #25 to allow non-confirmed messages

### LINKED ISSUE #25: Allow messaging to be optional
In some cases, it may make sense to "fire and forget" the message, not needing to wait for confirmation that the message was queued up. Confirmation requires processing overhead For non-critical messages, going as fast as possible and not failing the primary function of an application can be important. These would be "nice to have" messages.

Ref: http://rubybunny.info/articles/extensions.html#publisher_confirms_publisher_acknowledgements

### Use Case

Non-user facing application instrumentation (stats collection).

### PR DESCRIPTION
**Pull request by ryanwi**
In order to support use cases that need higher-throughput, and no exceptions for less critical messages, allow message confirmation to be optional.  This means messages could be dropped, but also means the application producing the message will  not fail because of a dropped message, which could be a valid use case.

### CODE REVIEW

**Comment by ryanwi** [comment]
@semmons99 Here's the patch to allow emque-stats to not cause application failures due to stats messages being dropped. This aligns with the stats use case, like StatsD, where we don't want a failure to send stats to cause the application to fail.

We won't capture the errors, so that's the tradeoff. It's interesting because we're turning off the publisher confirms feature, there's no way to know if it failed or not, and capture the error in Honeybadger.

If we want to capture the error, and still not fail the app due to stats failure, it's possible. In that case, we'd still use confirms, but use the flag to capture the error and log it, but not fail the application.

**Comment by semmons99** [comment]
I’m okay going with this. Perhaps we can find some way to monitor how long
it’s been since stats were received or something. I really don’t anticipate
a problem though.


*Shane Emmons* | Director of Technology and Principal Architect
TeamSnap - The easiest way to manage your team
(810) 834-9542 | shane@teamsnap.com | What is TeamSnap?
<http://www.youtube.com/watch?v=fx0vRXYGijU>

**Comment by ryanwi** [comment]
We can look at having monit monitor the graphite data. Should be fairly straightforward. @semmons99 you want all that email footer in this public repo?

**Comment by semmons99** [comment]
I wish it wouldn't show up :smile:

**Comment by ryanwi** [comment]
@kyleries @randy-girard Can you guys review as well since this has impacted you?

This change is to allow applications to have non-mandatory messages. Meaning that the application will not fail if the message cannot be routed.

**Comment by ryanwi** [comment]
@kyleries @dmvt @semmons99 coming full circle on this. Take a look and see what you think. You can read that last commit for more background (https://github.com/teamsnap/emque-producing/commit/c349829ed4b63f2516246a9ff69fd5ed2c6fbe42)

For an example implementation, see https://github.com/teamsnap/emque-stats/pull/6/files

File: lib/emque/producing/message/message.rb [hunk 1]
```diff
@@ -64,6 +76,10 @@ def message_type
         self.class.read_message_type
       end
 
+      def raise_message_failure
+        self.class.read_raise_message_failure
```
Comment (dmvt) [inline lib/emque/producing/message/message.rb]: This seems like it's designed as a boolean response. If so, I suggest:

```ruby
def raise_message_failure?
  self.class.read_raise_message_failure ? true : false
end
```

**Comment by dmvt** [comment]
I like this, although looking at the implementation, the 'message' part of the name seems repetitive. Perhaps 'raise_on_failure'?

Either way, I like it. :+1:

File: lib/emque/producing/message/message.rb (hunk 1 above)
Comment (ryanwi) [inline lib/emque/producing/message/message.rb]: It does default to true in the class method: https://github.com/teamsnap/emque-producing/pull/26/files#diff-eaa13cbc2d2da6e4e638a20047ce0b4dR31

**Comment by ryanwi** [comment]
Updated the naming a bit per your suggestions Dan.
